### ISSUE TITLE
jvm_settings file can (correctly) show duplicate values

### ISSUE THREAD

**Issue by markcurtis1970** [dremio/dremio-diagnostic-collector#101]
This isn't actually a problem with the code here, we are actually faithfully displaying what the `jps` command outputs. However if a Kubernetes deployment adds in `Xmx` it will be shown twice. This is expected because the JVM will only even take the last option. However it could potentially be confusing.

Previously we used `jcmd` which does give a true depiction of the JVM settings but we did run into some issues here.

I guess I'd like to discuss wether we thing this duplication is enough of an issue - especially when trying to 100% validate from the JVM what values it is indeed running with

**Comment by rsvihladremio** [comment]
I think the fact we have the jfr which has the calculated values we should be good here
