### ISSUE TITLE
collect list of mounted disks using "mount"

### ISSUE THREAD

**Issue by mxmarg** [dremio/dremio-diagnostic-collector#117]
can be added as separate paragraph to diskusage.txt file

**Comment by markcurtis1970** [comment]
@mxmarg would `lsblk` be a good alternative or do you need to see mount options (which mount will show)

**Comment by mxmarg** [comment]
It seems like lsblk (with the right flags) would return the same or even better info
After a quick google, something maybe like `lsblk -o NAME,FSTYPE,UUID,RO,RM,SIZE,STATE,OWNER,GROUP,MODE,TYPE,MOUNTPOINT,LABEL,MODEL` ?

**Comment by markcurtis1970** [comment]
Ok ive tagged this as an enhancement - dont see why it should be too difficult to implement as long as the base images (docker or bare metal) support `lsblk` if not then mount will suffice. We could do either / or?

**Comment by mxmarg** [comment]
Either / or is totally fine with me :)
