### ISSUE TITLE
Unexpected use of "/tmp" path

### ISSUE THREAD

**Issue by suiterdevin** [dremio/dremio-diagnostic-collector#123]
There's a place where an interim output path points to the /tmp path while DDC is running. Existing output path options don't update this which should be fixed.

https://github.com/dremio/dremio-diagnostic-collector/blob/5658910671c8ebfd0e2277ce3ee752caf49c0af6/cmd/root/helpers/healthcheck_strategy.go#L40

**Comment by markcurtis1970** [comment]
@suiterdevin - ok thank you. Can you give some more context on this? Are we seeing use of the `/tmp/<generated_id>` that is defined by https://pkg.go.dev/os#MkdirTemp instead of parameters passed in for `--transfer-dir` ?

**Comment by markcurtis1970** [comment]
Ok verified the issue like so, ran a collection on a test cluster with the following tmp dir settings, echoed out into the `ddc.log`

```
INFO:  2023/11/07 10:31:03 root.go:158: cli command: ./bin/ddc -k -c app=dremio-coordinator -e app=dremio-executor --transfer-dir /opt/dremio/data/ddc-temp/ -t
...
INFO:  2023/11/07 10:31:51 capture.go:99: successfully copied ddc.yaml to host dremio-master-0 at /opt/dremio/data/ddc-temp/ddc.yaml
```

We also see this in the ddc log from the pod:

```
DEBUG: 2023/11/07 10:31:54 dremio_conf.go:27: Collecting Configuration Information from dremio-master-0 ...
DEBUG: 2023/11/07 10:31:54 dremio_conf.go:34: masking passwords in dremio.conf
DEBUG: 2023/11/07 10:31:54 config_mask.go:104: ... Removing potential secrets from /tmp/ddc/20231107-103153/configuration/dremio-master-0/dremio.conf
DEBUG: 2023/11/07 10:31:54 dremio_conf.go:50: ... Collecting Configuration Information from dremio-master-0 COMPLETED
INFO:  2023/11/07 10:31:54 thread_pool.go:84: 1/15 tasks completed
```

Therefore _locally_ on the container (or node) we are not passing through the transfer dir. Most of the time this will work silently. However with some customers the tmp dir might have a `noexec` mount option or just not have enough space

We should add a check here to make sure if the conf key is set to honour it locally too

**Comment by markcurtis1970** [comment]
Further tests show that setting:

```
tmp-output-dir: "/opt/dremio/data/ddc-temp"
tarball-out-dir: "/opt/dremio/data/ddc-temp"
```
in the `ddc.yaml` and the `--transfer-dir` on the command seems to achieve the same without any code changes

**Comment by markcurtis1970** [comment]
@suiterdevin - can you comment on the above? Cheers!

**Comment by markcurtis1970** [comment]
Re-opening since the tmp path is not fixed, in fact rolled back in #129

**Comment by ianils** [comment]
Hi @markcurtis1970  

So we are using `os.MkdirTemp`  then setting the environment variable  TMPDIR to point to a different dir other than /tmp would address the issue ?  Although thats not going to get pushed via ssh so not very useful :(  - potentially set it ~/dremio/.ssh/environment I guess on each executor - but that requires sshd to have PermitUserEnvironment set to true ..  even then with k8s it may not persist .  .

**Comment by markcurtis1970** [comment]
@ianils yes correct we are using that standard go function to find the tmp dir. Its called in a few places in the code, so what we need to do is have that same code check the config first to see if its set, and use that then if not fall back to `os.MkdirTmp`. Theres a few places this is done and it also creates some complexities in the unit tests.

**Comment by rsvihladremio** [comment]
ok because this was a bit sprawling across the code base and because the use case also includes running ddc FROM the coordinator we had to take care of yet another usage of /tmp (namely on the client to create the single tarball from all of the individual tarballs) we have made several PRs to make this more digestible of a change, and more easily understandable

**Comment by rsvihladremio** [comment]
all related work is completed
