### ISSUE TITLE
investigate using  /opt/dremio/bin/dremio-admin backup -j -l -d /tmp

### ISSUE THREAD

**Issue by rsvihladremio** [dremio/dremio-diagnostic-collector#136]
dremio-admin backup could replace nearly all or most of the REST API usage and could in theory vastly simplify the collection process as well as the ease of use. Investigate this possiblity

**Comment by markcurtis1970** [comment]
The big wrinkle here is the time it takes for a backup to run. Would this impact the collection time of DDC, if so then it might be something we should "option" in?

**Comment by rsvihladremio** [comment]
yeah agreed this takes way too long and backs up a lot more than we need and the cluster needs to be online; closing
