### ISSUE TITLE
Pull in cluster-id and dremio version to summary.json

### ISSUE THREAD

**Issue by markcurtis1970** [dremio/dremio-diagnostic-collector#142]
The version and cluster Id isnt readily available unless you use the API, which in turn requires a PAT token. In the absence of this we should try to discover  this in a way that negates the need for a token, if possible

**Comment by rsvihladremio** [comment]
at this point this task is easier and just needs to pull from the cluster-stats.json

**Comment by rsvihladremio** [comment]
actually this is just maybe not necessary .. closing

**Comment by rsvihladremio** [comment]
this would be a nice to have and we already have processing parsing this out.. going to do the work to fix this and get it back into summary.json
