### ISSUE TITLE
Environment Variable dremioLogDirKeyBackup := DREMIO_LOG_DIR never used as Backup

### ISSUE THREAD

**Issue by FrederikJobbst** [dremio/dremio-diagnostic-collector#177]
If the primary dremioLogDirKey is not found (function extractValue returns error and empty string), the function is exited and the backup key is not checked afterwards:

https://github.com/dremio/dremio-diagnostic-collector/blob/bf5c495c160330e46be4da373c4772d5b4e5b4c2/cmd/local/conf/conf.go#L518C1-L527C3

**Comment by rsvihladremio** [comment]
Thanks you are correct and this is an easy fix we will just log instead

**Comment by FrederikJobbst** [comment]
The issue is not closed with #179 because change was made at the wrong place, `simplelog.Warningf` must be 5(at 519) lines later

**Comment by markcurtis1970** [comment]
@FrederikJobbst yep I got this - oversight on my part. Apologies

**Comment by markcurtis1970** [comment]
@FrederikJobbst - opened https://github.com/dremio/dremio-diagnostic-collector/pull/182 - this should resolve the issue, We've not had bandwidth to write tests around the ENV vars yet properly but thats our intention.

Lmk if you have questions
