### ISSUE TITLE
Support passing in pat with masked flag

### ISSUE THREAD

**Issue by markcurtis1970** [dremio/dremio-diagnostic-collector#46]
For example instead of using PAT token in clear text in ddc.yaml.

Workaround for now should be to pass in token on command line

**Comment by rsvihladremio** [comment]
I think we should actually remove the option for a pat from the yaml and only allow it to be passed in via a flag that hides the password, this also means that we need to update the docs around this flag

**Comment by rsvihladremio** [comment]
changing my mind on removing it. there will be people who that is their preference nonetheless but I think adding the option to be a masked flag is nice..this also means that the current method for disabling REST via using a blank pat when submitting local-collect to executors will have to go away and be replaced with something else (detection of environment, etc)
