### ISSUE TITLE
Oracle java seems to need additional parameter for file when dumping

### ISSUE THREAD

**Issue by markcurtis1970** [dremio/dremio-diagnostic-collector#93]
When using oracle java 8 the following is seen in the `ddc.log` file

```
DEBUG: 2023/07/20 14:00:01 jfr.go:42: ... stopping JFR mc-ddc-1
ERROR: 2023/07/20 14:00:01 thread_pool.go:78: Failed to execute job: unable to dump JFR due to error command execution failed: exit status
1
```

On the command line we see this (several attempts leave the JFRs running)

```
$ jcmd 3313725 JFR.check
3313725:
Recording: recording=1 name="DREMIO_JFR" filename="/tmp/ddc/20230720-124758/jfr/mc-ddc-1.jfr" compress=false maxage=1m (running)

Recording: recording=2 name="DREMIO_JFR" filename="/tmp/ddc/20230720-135800/jfr/mc-ddc-1.jfr" compress=false maxage=1m (running)

Recording: recording=3 name="DREMIO_JFR" filename="/tmp/ddc/20230720-141258/jfr/mc-ddc-1.jfr" compress=false maxage=1m (running)
```

If I mimic the command manually

```
$ jcmd 3313725 JFR.dump name="DREMIO_JFR"
3313725:
java.lang.IllegalArgumentException: The option 'filename' is mandatory.
```

Adding the additional filename

```
$ jcmd 3313725 JFR.dump name="DREMIO_JFR" filename="/tmp/ddc/20230720-124758/jfr/mc-ddc-1.jfr"
3313725:
Dumped recording "DREMIO_JFR", 4.7 MB written to:

/tmp/ddc/20230720-124758/jfr/mc-ddc-1.jfr
```

**Comment by rsvihladremio** [comment]
confirmed this behavior is different in later versions of the JDK https://bugs.openjdk.org/browse/JDK-8220657 and in jdk 11 it will actually _break_ if we specify the filename on dump (I'm assuming this is related to it being set on start). 

We could revisit this later, but I think this is a rather tricky issue, in the end i'd rather the JFR fail in the very odd corner that someone is running an old JDK 8

**Comment by rsvihladremio** [comment]
also further 

https://bugs.openjdk.org/browse/JDK-8221485

_**It may be worth mentioning (in the documentation) that a filename is generated if the filename parameter is omitted, and that a directory can be used as a filename and the file will be generated in that directory This is important for users who want to automate dumps in script, for example in a cronjob. For an example, see**_


I'm calling the behavior you're seeing with the version of the Oracle JDK 8 that they're using a bug at this point, this cuts against documented behavior, breaks later versions of the JDK and does not seem to be needed in any case

**Comment by rsvihladremio** [comment]
Final note.. definitely sure this is a bug in the oracle jdk version as it cuts againt the jdk8 docs

https://docs.oracle.com/javase/8/docs/technotes/guides/troubleshoot/tooldescr006.html
<img width="705" alt="Capture d’écran 2023-07-20 à 18 55 06" src="https://github.com/dremio/dremio-diagnostic-collector/assets/105286284/18ffd18e-bc6d-4216-b5ac-24c43ef2c8e9">
